### ISSUE TITLE
Write publication

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#20]
## Logic
To finish the publication for AutoPlate the following steps need to be completed

## Tasks
- [x] Write 1st draft
- [x] Adress David's comments
- [x] Add references
- [x] Add example data #21 
    - [x] Update plots in publication
    - [x] Write summary text of example data
- [x] Be more concise and precise
- [x] Update based on #25 and #26
- [x] Check with Grammarly
- [x] 2nd review from David
- [x] Update based on ELLA support
- [x] Review from George (fact check)
- [ ] Write in LaTeX?
- [x] Convert to word doc format and update references
