### ISSUE TITLE
Add example data

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#21]
## Logic
It would be useful to have example data to
1. Allow users to try out AutoPlate
2. To publish as part of the publication and use the data for all of the plots etc.

## Tasks
- [x] Improve drc plot for multiple viruses #23
- [x] Ask George questions re the example data
     - [x] How can the same mouse (eg mouse 45) be inoculated with two different inoculates? Rename them
![image](https://user-images.githubusercontent.com/32334279/103532869-ee434380-4e83-11eb-8ae5-2575c9e9f757.png)
    - [x] How to analyse plates with no V/C controls? Duplicate V/C controls from another plate?
![image](https://user-images.githubusercontent.com/32334279/103532893-0024e680-4e84-11eb-927a-0d86b69bff79.png)
    - [x] How should the drc plot look?
    - [x] How to interpret the data for publication? Summary?
- [x] Investigate inverse antibody drc curve for one of the viruses
- [ ] Make the example data as accurate and clean as possible
    - [ ] Add new data (3 new plates)
    - [x] Remove `Trace 4`?
    - [x] Exclude empty wells
    - [ ] Ensure all data is entered
    - [ ] Ensure all variables are correct
- [x] Add simple examples of rawdata + ELLA data
- [x] Make sure that simple data works with the report
- [x] Add a **`Use example data`** button to AutoPlate
    - [x] Allow re-uploading of dataset
