### ISSUE TITLE
Release AutoPlate

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#22]
## Logic
The follwing is a checklist of things which would be worth considering before publishing/releasing AutoPlate

## Tasks
- [ ] Merge to `main` branch
    - [x] Update example data link to `main` branch 
- [ ] Update `suggests` packages eg `shiny`, `pkgdown` etc.
- [x] Add Shiny app link to docs website
- [ ] Inputs
    - [ ] Standardise input formats
    - [ ] Use the same method to generate the plate numbers for ELLA + pMN data (single func)
    - [ ] Use `rename_cols` func to find any depreciated column names and replace with new ones
- [ ] Add publication image to website
- [ ] Update code coverage to main or dev branch
- [ ] Redeploy and make sure app (inc. report) still works
- [x] Make the GitHub repository public
- [ ] Make a GitHub release
- [ ] Custom domain name with proxy server?
- [ ] Upgrade RShiny account to increase months usage from 25hrs -> 100hrs (see [here](https://www.shinyapps.io/?_ga=2.145243698.72725))
- [ ] Make a HTML docs page?
- [ ] Make a demo video?
- [ ] Add automated CI/CD testing
    - [ ] Add GitHub actions
    - [ ] Write tests
- [x] Update readme (generated from RMD)
- [ ] Add `vignettes` back (was removed because it was causing [this issue](https://github.com/PhilPalmer/AutoPlate/runs/1750668384))
- [ ] Go through enhancements #2 
- [x] Add logo
- [ ] Update images to ones using example data
- [ ] Fix notes from R cmd / devtools check (`no visible binding for global variable` ...)
- [ ] Golem 
    - [ ] Add news and code of conduct files, recommended deps, package data, code coverage?
    - [ ] Use [`with_red_star`](https://engineering-shiny.org/matters.html#c.-inputs-and-errors) to denote required arguments
