### ISSUE TITLE
Improve drc plot for multiple viruses

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#23]
## Logic
Currently, if a user tries to plot a dataset containing multiple viruses in AutoPlate the plot will look like this
![image](https://user-images.githubusercontent.com/32334279/103534184-54c96100-4e86-11eb-9641-5d44e08ae3f1.png)

This is because only one plot can be displayed (rather than a plot for each primary) and so I am using `facet_wrap(c("inoculate","primary"))` to display all of the different viruses

However, this plot is not correct as the curves are on separate plots and I am not sure why there are multiple lines and why the lines are drawn even if no data points are present for that incoluate x primary combination

## Potential solutions
1. Ideally I would be able to change the value of `facet_wrap` so that they are all plotted within a single plot, for example, I could try `facet_wrap(~primary)` but I am not sure if this is correct
![image](https://user-images.githubusercontent.com/32334279/103534523-edf87780-4e86-11eb-893e-667586e86b33.png)
2. Alternatively, I could filter for each primary, plot them individually and then combine the plots with [`grid.arrange`](https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html)
3. Or I could provide a dropdown menu to display a given primary

## Tasks
- [x] Check `new_data$pred` values because predictions are being shown for all primaries
- [x] Otherwise try solution number 3 to have a separate plot for each primary which can be selected from a dropdown menu as this seems easiest
    - [x] Implement dropdown for each of the different viruses
    - [x] Filter to keep just the virus selected from the dropdown
    - [x] Make sure it displays for both DRC & IC50 plots
    - [x] Update report
        - [x] Update plot colours
        - [x] Create separate plots for each virus
