### ISSUE TITLE
Update features names

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#24]
## Logic
Updating the features names eg `incolate`/`subject` may useful or three reasons:
1. Features such as `subject` could be made more **intuitive**
2. Features such as `inoculate` could be **generalised** for groups who aren't using vaccines
3. Features such as `subject` could be made more **consistent** between the AutoPlate application and publication

## Tasks
- [x] Update feature names within AutoPlate
    - [x] `subject`/mouse → `sample_id`/sample
    - [x] `inoculate` → `treatment`
    - [x] `primary` → `virus`?
    - [x] `study` → `experiment_id`
- [x] Update docs
- [x] Update example data
- [x] Ensure backwards compatibility by replacing old names with new names on upload
- [x] Update feature names within the publication
