### ISSUE TITLE
Refactor with golem

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#25]
## Logic
To improve the structure of the app codebase and make it more maintainable the [golem](https://engineering-shiny.org/golem.html) R library could be used

## Tasks
- [x] Create new github branch?
- [ ] Remove all of the existing codebase
- [x] Generate a new template with Golem
- [x] Copy the old codebase into the new one
- [x] Get gh actions test to work
- [x] Add more tests
    - [x] Package installation - different platforms?
    - [x] `testthat` test
    - [x] code coverage
    - [ ] lintr
