### ISSUE TITLE
Allow all features to be set using the plate data table

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#26]
## Logic
To allow more flexible setting of features (such as having multiple samples/subject per column) all features could be set using the plate data table, as follows:

1. The user selects an existing feature such as the plate types
2. The data for that feature for all of the wells loads in 96-well plate format
3. The user can then modify this data in any way they wish either individually for each plate or use the `Template` plate to modify all plates
![image](https://user-images.githubusercontent.com/32334279/103552544-f90dd080-4ea3-11eb-9f92-eca33bb1ebc8.png)

## Tasks
- [x] Allow all features to be set using the 96-well plate table
    - [x] Dropdown?
    - [x]  Refactor/generalise the plate data functions so that they can be used for any feature
    - [x] Fetch data
    - [x] Update data
    - [x] Allow multiple changes
    - [x] Update documentation
- [x] Add template to set all plates (with default values)
    - [x] Create data store for template values eg reactiveValues object in similar format to main assay data frame
    - [x] Fetch and display template data when the user clicks on the template tab
    - [x] If user updates template update all plates 

~- [ ] Add feedback to show which features have been set~
~- [ ] Add [syntax hightling](https://stackoverflow.com/questions/58746194/shiny-and-rhandsontable-conditional-cell-column-formatting-based-on-column-sum) so that the plate data can replace the QC step~
~- [ ] If everything above is implemented and works well remove the QC step~
