### ISSUE TITLE
Add support for ELLA assay

### ISSUE THREAD

**Issue by PhilPalmer** [PhilPalmer/AutoPlate#30]
## Logic
Currently, AutoPlate only supports the pMN assay. Adding support for the ELLA assay would be very useful for the two labs and make AutoPlate useful to a much wider group of people. As ELLA uses a different input format, plate layout and horizontal dilutions rather than vertical the following changes need to be made

## Tasks
- [x] Get data & scripts
    - [x] Excel plain text input files
    - [x] Code to convert Excel -> platelist
    - [x] PRISM files
- [x] Add dropdown to select assay type
    - [x] Add dropdown
    - [x] Add reactive values to store assay type
- [x] Add support of Excel plain text input
    - [x] Convert input to assay dataframe platelist format if assay type is ELLA
- [x] Support horizontal dilutions
    - [x] Prevent dilutions table from overwriting plate data
    - [x] Use horizontal dilutions in plate data table 
- [x] Update default plate layout if ELLA assay (see below)
    - [x] Types (used for normalisation)
    - [x] Samples (2 rows per sample i.e. 4 samples per plate)
- [x] Fix bug in plots when no positive control is present 
- [x] Fix R cmd check vignettes warning
- [x] Add documentation for supported input formats
- [x] Update text in documentation 
- [x] Add update all wells option
- [x] Add support for updated ELLA format
- [x] Update plate numbers for ELLA data to be the same as pMN
- [x] Add link to the AutoPlate docs

Types:
![image](https://user-images.githubusercontent.com/32334279/109168168-72c08d00-7776-11eb-9458-fd1b53a4ff0f.png)

Samples:
![image](https://user-images.githubusercontent.com/32334279/109168482-c632db00-7776-11eb-838d-4e30a92103e2.png)
